version: '3.8'

services:
  mongodb:
    build:
      context: ./database       
      dockerfile: Dockerfile      
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env                      

volumes:
  mongodb_data:
